workflows:
  build-android-release:
    name: Build Android Release APK
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.bluewallet.app"
        GRADLE_OPTS: "-Xmx4096m"
        CM_KEYSTORE: Encrypted()  # ← wird aus Environment geladen
        CM_KEYSTORE_PASSWORD: Encrypted()
        CM_KEY_ALIAS: Encrypted()
        CM_KEY_PASSWORD: Encrypted()
      node: 18.16.0
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build signed release APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
