workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.bluewallet.app"
        GRADLE_OPTS: "-Xmx4096m"
      node: 18.16.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
