workflows:
  build-android-release:
    name: Build Android Release APK
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.bluewallet.app"
        GRADLE_OPTS: "-Xmx4096m"
      node: 18.16.0
      java: 17

    android_signing:
      - keystore: $CM_KEYSTORE
        keystore_password: $CM_KEYSTORE_PASSWORD
        key_alias: $CM_KEY_ALIAS
        key_password: $CM_KEY_PASSWORD

    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build signed release APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
